apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  analysisTemplateEnabled: true

spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause: {} # Pauses indefinitely until manually promoted
      - analysis:
          templates:
          - templateName: rollouts-demo-analysis
          args:
          - name: THRESHOLD
            value: "0.02"
          - name: INTERVAL
            value: "5m"
      - setWeight: 30
      - pause: {duration: 30s}
      - setWeight: 55
      - analysis:
          templates:
          - templateName: rollouts-demo-analysis
          args:
          - name: THRESHOLD
            value: "0.02"
          - name: INTERVAL
            value: "5m"
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      - setWeight: 100
      - analysis:
          templates:
          - templateName: rollouts-demo-analysis
          args:
          - name: THRESHOLD
            value: "0.02"
          - name: INTERVAL
            value: "5m"
      canaryMetadata:
        labels:
          rollout-phase: canary
      stableMetadata:
        labels:
          rollout-phase: stable
    spec:
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
